Model ArrayDecoding Builder as an enum
airbnb/ResilientDecoding pull request #16
Opened 2020-04-18 20:37 UTC by fdiaz

This addresses this comment https://github.com/airbnb/ResilientDecoding/pull/11#discussion_r410524805

We're both not fans of the `Builder` approach, so this is an attempt to reword that with an `enum` instead to hopefully make things simpler without changing the API too much.

Let me know what you think @GeorgeLyon

2020-04-18 20:37 UTC, fdiaz commented on Sources/ResilientDecoding/ResilientPropertyLevelErrors.swift
> +      Value == [T]
Indenting this file with Xcode

2020-04-18 20:37 UTC, fdiaz commented on Sources/ResilientDecoding/ResilientPropertyLevelErrors.swift
> +    .map { $0.element.element }
Indenting this file with Xcode

2020-04-19 05:01 UTC, GeorgeLyon requested changes
Thanks for putting this together, but I'm not sure this simplifies things. Most of my feedback is qualitative, but I think leaking the internal state of `Builder/State` and not having it namespaced are strict negatives.
Even if I weren't leaning negative on this, I think we should have a higher bar for no-behavior-change PRs (to clarify, I consider the removal of a public underscored protocol and conformance from my previous PR to be "behavior change") and in my mind that high bar should be fixing some concrete issue for folks contributing to the repository, which I'm not sure this PR meets. Though I have a feeling that the last statement will come back to bite me a few PRs from now...

2020-04-19 05:01 UTC, GeorgeLyon commented on Sources/ResilientDecoding/ResilientPropertyLevelErrors.swift
> +   Attempts to build the `ArrayDecodingError`, returns `nil` if all elements decoded successfully.
I think it is telling that you used "Build" here, leading me to think `Builder` is actually the correct abstraction to use.

2020-04-19 05:01 UTC, GeorgeLyon commented on Sources/ResilientDecoding/ResilientPropertyLevelErrors.swift
> +enum ArrayDecodingErrorState {
One thing I liked about `Builder` was that it was namespaced to `ArrayDecodingError` so we didn't have another top-level type. The other thing I liked was that the internal state of `Builder` was private, which is no longer the case if it becomes an `enum`.

2020-04-19 05:01 UTC, GeorgeLyon commented on Sources/ResilientDecoding/ResilientPropertyLevelErrors.swift
> + Builds an `ArrayDecodingError`. This type assumes you are decoding elements in order, and care must be taken that the `mutating` members are called in the correct order.
"Build" again.

2020-04-19 05:01 UTC, GeorgeLyon commented on Sources/ResilientDecoding/ResilientPropertyLevelErrors.swift
> +  var error: ArrayDecodingError? {
Why does the `ArrayDecodingErrorState` have an `error`? Seems to me like the `ArrayDecodingErrorState` should be the state of an `ArrayDecodingError`, whatever that means.

2020-04-19 05:01 UTC, GeorgeLyon commented on Sources/ResilientDecoding/ResilientPropertyLevelErrors.swift
> +  case none(count: Int)
I'm not sure the difference between `start` and `none` is immediately apparent, which is exacerbated by the fact that the internal state of this thing is no longer `private`.

2020-04-19 05:30 UTC, closed without merging

2020-04-19 05:34 UTC, fdiaz commented
> I think leaking the internal state of Builder/State and not having it namespaced are strict negatives

I thought this was what we wanted instead of having a mutable index internally, but I think I misunderstood.

 > and not having it namespaced are strict negatives.

This could have been easily fixed by putting it back inside the namespace. There's nothing technically preventing us from doing this.

> Even if I weren't leaning negative on this, I think we should have a higher bar for no-behavior-change PRs

I'm not sure I follow. This doesn't do any behavior changes in the public facing API.

> and in my mind that high bar should be fixing some concrete issue for folks contributing to the repository

I was hoping this type was easier to maintain given we didn't both didn't like the `Builder`

Since your reaction is clearly negative to this path I'm gonna put this idea off.

I'd love to get rid of the Builder at some point since that API is not great, but since its internal it's not a big problem either.